const jobsData = [
    {
      id: 1,
      title: "Frontend Developer",
      jobDes:
        "We are seeking a skilled Frontend Developer with expertise in React and Tailwind CSS. You will be responsible for designing and developing interactive user interfaces, ensuring a seamless user experience, and optimizing web applications for performance and responsiveness. Join our team and work on exciting projects that shape the future of web development.",
      noOfApplied: "15",
      experience: "2+",
      location: "Remote",
      jobType: "Full-time",
      industry: "Tech",
      skills: "React, JavaScript, Tailwind CSS",
      postedAt: "2024-02-20",
      creator: "Tech Corp",
    },
    {
      id: 2,
      title: "UI/UX Designer",
      jobDes:
        "We are looking for a creative UI/UX Designer to craft engaging and intuitive user experiences. Your role will involve wireframing, prototyping, and designing visually appealing interfaces that enhance user interaction. If you have an eye for design and a passion for improving digital products, we would love to have you on board.",
      noOfApplied: "21",
      experience: "3+",
      location: "Hybrid",
      jobType: "Part-time",
      industry: "Design",
      skills: "Figma, Adobe XD, Prototyping",
      postedAt: "2024-02-25",
      creator: "Design Studio",
    },
    {
      id: 3,
      title: "Backend Developer",
      jobDes:
        "Join our team as a Backend Developer and help build robust and scalable server-side applications. You will be responsible for developing APIs, optimizing database performance, and ensuring seamless integration with frontend applications. If you enjoy working with backend technologies and solving complex problems, this is the role for you.",
      noOfApplied: "10",
      experience: "4+",
      location: "Onsite",
      jobType: "Full-time",
      industry: "Software",
      skills: "Node.js, Express, MongoDB",
      postedAt: "2024-02-18",
      creator: "Startup X",
    },
    {
      id: 4,
      title: "Product Manager",
      jobDes:
        "We are seeking a strategic and detail-oriented Product Manager to lead and execute product roadmaps. You will work closely with cross-functional teams to define product vision, prioritize features, and ensure successful product launches. If you have strong analytical skills and a passion for delivering impactful solutions, apply now.",
      noOfApplied: "8",
      experience: "5+",
      location: "Remote",
      jobType: "Full-time",
      industry: "Business",
      skills: "Agile, Scrum, Leadership",
      postedAt: "2024-02-22",
      creator: "Business Solutions",
    },
    {
      id: 5,
      title: "DevOps Engineer",
      jobDes:
        "We are looking for a skilled DevOps Engineer to streamline development workflows and manage cloud infrastructure. You will be responsible for setting up CI/CD pipelines, automating deployments, and ensuring system security. If you have expertise in cloud technologies and love optimizing development processes, we want to hear from you.",
      noOfApplied: "12",
      experience: "3+",
      location: "Remote",
      jobType: "Contract",
      industry: "Cloud Computing",
      skills: "AWS, Docker, Kubernetes",
      postedAt: "2024-02-28",
      creator: "CloudTech",
    },
    {
      id: 6,
      title: "Mobile App Developer",
      jobDes:
        "We are hiring an experienced Mobile App Developer proficient in React Native and Flutter. Your role will involve building high-performance mobile applications for iOS and Android platforms. If you enjoy creating user-friendly mobile experiences and working on innovative projects, this position is perfect for you.",
      noOfApplied: "18",
      experience: "2+",
      location: "Remote",
      jobType: "Full-time",
      industry: "Mobile Development",
      skills: "React Native, Flutter, Android/iOS",
      postedAt: "2024-02-26",
      creator: "App Ventures",
    },
    {
      id: 7,
      title: "Data Analyst",
      jobDes:
        "We are seeking a detail-oriented Data Analyst to extract insights from complex datasets. Your role will involve data visualization, trend analysis, and generating reports to drive business decisions. If you have strong analytical skills and a passion for working with data, apply today.",
      noOfApplied: "25",
      experience: "3+",
      location: "Hybrid",
      jobType: "Full-time",
      industry: "Analytics",
      skills: "SQL, Python, Power BI",
      postedAt: "2024-02-24",
      creator: "Analytics Firm",
    },
    {
      id: 8,
      title: "Marketing Specialist",
      jobDes:
        "We are looking for a dynamic Marketing Specialist to develop and execute digital marketing strategies. Your role will include managing social media campaigns, optimizing SEO, and running paid ads. If you are passionate about brand growth and digital marketing, this role is for you.",
      noOfApplied: "30",
      experience: "2+",
      location: "Onsite",
      jobType: "Full-time",
      industry: "Marketing",
      skills: "SEO, Google Ads, Social Media",
      postedAt: "2024-02-23",
      creator: "Brand Growth",
    },
    {
      id: 9,
      title: "Cybersecurity Analyst",
      jobDes:
        "We are hiring a Cybersecurity Analyst to ensure the security of our systems and networks. Your role will include conducting security assessments, identifying vulnerabilities, and implementing protective measures. If you are passionate about cybersecurity and data protection, apply now.",
      noOfApplied: "14",
      experience: "3+",
      location: "Remote",
      jobType: "Contract",
      industry: "Cybersecurity",
      skills: "Penetration Testing, Network Security",
      postedAt: "2024-02-27",
      creator: "SecureTech",
    },
    {
      id: 10,
      title: "AI/ML Engineer",
      jobDes:
        "Join our AI team as a Machine Learning Engineer and work on cutting-edge AI solutions. You will develop machine learning models, analyze large datasets, and build intelligent applications. If you are passionate about AI and innovation, we would love to have you.",
      noOfApplied: "9",
      experience: "4+",
      location: "Hybrid",
      jobType: "Full-time",
      industry: "Artificial Intelligence",
      skills: "Python, TensorFlow, Deep Learning",
      postedAt: "2024-02-21",
      creator: "AI Innovations",
    },
    {
      id: 11,
      title: "Blockchain Developer",
      jobDes:
        "We are looking for a Blockchain Developer to develop and maintain smart contracts and decentralized applications. If you have experience with Ethereum, Solidity, and Web3.js, join our team and work on the future of blockchain technology.",
      noOfApplied: "10",
      experience: "3+",
      location: "Remote",
      jobType: "Full-time",
      industry: "Blockchain",
      skills: "Solidity, Ethereum, Web3.js",
      postedAt: "2024-02-28",
      creator: "Crypto Solutions",
    },
    {
      id: 12,
      title: "Technical Support Engineer",
      jobDes:
        "Hiring a Technical Support Engineer to assist customers with troubleshooting and technical queries. If you enjoy problem-solving and have excellent communication skills, this role is a great fit for you.",
      noOfApplied: "22",
      experience: "2+",
      location: "Onsite",
      jobType: "Full-time",
      industry: "IT Support",
      skills: "Troubleshooting, Customer Service, Linux",
      postedAt: "2024-02-22",
      creator: "Tech Assist",
    }
  ];
  
  export default jobsData;
  